steps:
   - id: 'Execute Configuration'
     name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     entrypoint: bash
     args: [ './massage.sh', '$_REGION' ]
     
   - id: 'Build Image'
     name: 'gcr.io/cloud-builders/docker'
     args: [ 'build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/docker-builds/builder', '.' ]
     
   - id: 'Deploy Frontend'
     name: gcr.io/cloud-builders/gcloud
    entrypoint: 'scripts/deploy.sh'
    args: [ "frontend" ]
    env:
      - PROJECT_ID=${_PROJECT_ID}
      - BRANCH_TAG=${_BRANCH_TAG}
      - GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=${_TERRA_SA}
      - IMAGE_NAME=${_IMAGE_BASE}login:${_BRANCH_TAG}
    waitFor:
      - 'Build login Image'



logsBucket: "gs://${_PROJECT_ID}-build-reports/build-logs/frontend"
options:
  logging: GCS_ONLY
timeout: 1800s
substitutions:
  _REGION: northamerica-northeast1
  _IMAGE_BASE: $_REGION-docker.pkg.dev/${_PROJECT_ID}/docker-builds/
  _BUILD_NAME: $_REGION-docker.pkg.dev/${_PROJECT_ID}/docker-builds/builder
  _TERRA_SA: sa-terraform@${_PROJECT_ID}.iam.gserviceaccount.com